// Mapping of display names to topic slugs
export const TOPIC_OPTIONS = {
  'Array': 'array',
  'Backtracking': 'backtracking',
  'Biconnected Component': 'biconnected-component',
  'Binary Indexed Tree': 'binary-indexed-tree',
  'Binary Search': 'binary-search',
  'Binary Search Tree': 'binary-search-tree',
  'Binary Tree': 'binary-tree',
  'Bit Manipulation': 'bit-manipulation',
  'Bitmask': 'bitmask',
  'Brainteaser': 'brainteaser',
  'Breadth First Search': 'breadth-first-search',
  'Bucket Sort': 'bucket-sort',
  'Combinatorics': 'combinatorics',
  'Counting': 'counting',
  'Counting Sort': 'counting-sort',
  'Data Stream': 'data-stream',
  'Depth First Search': 'depth-first-search',
  'Design': 'design',
  'Divide and Conquer': 'divide-and-conquer',
  'Doubly Linked List': 'doubly-linked-list',
  'Dynamic Programming': 'dynamic-programming',
  'Enumeration': 'enumeration',
  'Eulerian Circuit': 'eulerian-circuit',
  'Game Theory': 'game-theory',
  'Geometry': 'geometry',
  'Graph': 'graph',
  'Greedy': 'greedy',
  'Hash Function': 'hash-function',
  'Hash Table': 'hash-table',
  'Heap (Priority Queue)': 'heap-priority-queue',
  'Interactive': 'interactive',
  'Iterator': 'iterator',
  'Line Sweep': 'line-sweep',
  'Linked List': 'linked-list',
  'Math': 'math',
  'Matrix': 'matrix',
  'Memoization': 'memoization',
  'Merge Sort': 'merge-sort',
  'Minimum Spanning Tree': 'minimum-spanning-tree',
  'Monotonic Queue': 'monotonic-queue',
  'Monotonic Stack': 'monotonic-stack',
  'Number Theory': 'number-theory',
  'Ordered Set': 'ordered-set',
  'Prefix Sum': 'prefix-sum',
  'Probability and Statistics': 'probability-and-statistics',
  'Queue': 'queue',
  'Quickselect': 'quickselect',
  'Radix Sort': 'radix-sort',
  'Randomized': 'randomized',
  'Recursion': 'recursion',
  'Rejection Sampling': 'rejection-sampling',
  'Reservoir Sampling': 'reservoir-sampling',
  'Rolling Hash': 'rolling-hash',
  'Segment Tree': 'segment-tree',
  'Shortest Path': 'shortest-path',
  'Simulation': 'simulation',
  'Sliding Window': 'sliding-window',
  'Sorting': 'sorting',
  'Stack': 'stack',
  'String': 'string',
  'String Matching': 'string-matching',
  'Strongly Connected Component': 'strongly-connected-component',
  'Suffix Array': 'suffix-array',
  'Topological Sort': 'topological-sort',
  'Tree': 'tree',
  'Trie': 'trie',
  'Two Pointers': 'two-pointers',
  'Union Find': 'union-find'
};

export const TOPIC_DISPLAY_NAMES = Object.keys(TOPIC_OPTIONS);